schedule_birthday_notifications:
  cron: "0 * * * *"
  class: "BirthdayNotificationJobs::ScheduleBirthdayNotificationsJob"
  description: "Scan the User model and create a BirthdayNotification if today is their birthday"

send_birthday_notifications:
  cron: "0 * * * *"
  class: "BirthdayNotificationJobs::SendBirthdayNotificationsJob"
  description: "Send birthday notifications from the BirthdayNotification model"
